apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  #annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: cloudemy.local
    http:
      paths:
      # 프론트 라우팅
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80

      # ✅ 백엔드 API 라우팅
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend      # <--- 여기 Service 이름 = backend
            port:
              number: 8000     # <--- Service spec.port (지금 8000)
